vich_uploader:
    db_driver: orm

    mappings:
        avatar_images:
            uri_prefix: '%app.path.avatar_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.avatar_images%'
